steps:
- name: 'gcr.io/cloud-builders/go:debian'
  args: ['build', './cmd/kritis/signer']
  env: ['PROJECT_ROOT=github.com/soy-kyle/kritis']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: /bin/bash
  args:
    - -c
    - |
      cp signer integration/signer/ &&
      cd integration/signer &&
      ./signer_int.sh
  env: ['PROJECT_ID=$PROJECT_ID', 'BUILD_ID=$BUILD_ID']
  timeout: 900s
timeout: 1200s
